apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: braavos-camera-motioneye-pvc
  namespace: default
spec:
  volumeName: braavos-camera-pv
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: ""
  resources:
    requests:
      storage: 1024Gi