apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 0 # normally 1
  selector:
    matchLabels:
      app: plex
  serviceName: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: plexinc/pms-docker
        imagePullPolicy: Always
        # command: ["tail","-f","/dev/null"]
        ports:
         - containerPort: 32400
        volumeMounts:
          - mountPath: "/braavos"
            name: braavos
          - mountPath: "/dev/dri"
            name: dri
          - mountPath: "/config"
            name: plex-config
          # - mountPath: "/external"
          #   name: local
        securityContext:
          privileged: true
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 1000m
            memory: 2Gi
      volumes:
        - name: braavos
          persistentVolumeClaim:
            claimName: braavos-media-pvc
        - name: dri
          persistentVolumeClaim:
            claimName: dri-pvc
        # - name: local
        #   hostPath:
        #     path: /mnt/external/
        #     type: DirectoryOrCreate
      nodeSelector:
        graphics: dri
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: plex-config
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 40Gi
