apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: plex
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  serviceName: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex
        image: plexinc/pms-docker
        imagePullPolicy: Always
        ports:
         - containerPort: 32400
        volumeMounts:
          - mountPath: "/braavos"
            name: braavos
          - mountPath: "/dev/dri"
            name: dri
          - mountPath: "/config"
            name: plex-config
        securityContext:
          privileged: true
        resources:
          limits:
            memory: 2G
      volumes:
        - name: braavos
          persistentVolumeClaim:
            claimName: braavos-media-pvc
        - name: dri
          persistentVolumeClaim:
            claimName: dri-pvc
      nodeSelector:
        kubernetes.io/hostname: trainman
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: plex-config
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 40Gi