# pulled from https://github.com/richstokes/k8s-fah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tplink-prometheus
  labels:
    app: tplink-prometheus
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tplink-prometheus
  template:
    metadata:
      labels:
        app: tplink-prometheus
    spec:
      hostNetwork: true
      containers:
        - name: tplink-prometheus
          image: zibby/tplink-exporter:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: docker-hub