# pulled from https://github.com/richstokes/k8s-fah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tplink-dashboard
  labels:
    app: tplink-dashboard
spec:
  selector:
    matchLabels:
      app: tplink-dashboard
  template:
    metadata:
      labels:
        app: tplink-dashboard
    spec:
      hostNetwork: true
      containers:
        - name: tplink-dashboard
          image: jbarnett/tplink-energy-monitor:latest
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: docker-hub