# pulled from https://github.com/richstokes/k8s-fah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tplink-prometheus
  namespace: monitoring
  annotations:
    prometheus.io/scrape: "true" 
    prometheus.io/port: "8089"
  labels:
    app: tplink-prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tplink-prometheus
  template:
    metadata:
      labels:
        app: tplink-prometheus
    spec:
      hostNetwork: true
      containers:
        - name: tplink-prometheus
          image: zibby/tplink-exporter:latest
          ports:
            - containerPort: 8089
      imagePullSecrets:
        - name: docker-hub