apiVersion: v1
kind: Service
metadata:
  name: network-tools
spec:
  type: ClusterIP
  selector:
    app: network-tools
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
