apiVersion: v1
kind: Service
metadata:
  name: tplink-prometheus
spec:
  type: ClusterIP
  selector:
    app: tplink-prometheus
  ports:
    - name: tplink
      protocol: TCP
      port: 8089
      targetPort: 8089
