apiVersion: v1
kind: PersistentVolume
metadata:
  name: braavos-camera-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  capacity:
    storage: 16Ti
  nfs:
    path: /nfs/Camera/
    server: braavos.jura
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: braavos-media-pv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadOnlyMany
  - ReadWriteMany
  capacity:
    storage: 16Ti
  nfs:
    path: /nfs/media/
    server: braavos.jura
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: dri-pv
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 256Mi
  hostPath:
    path: /dev/dri
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem