apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: tyzbit@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    http01: {}