apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - clusterissuer.yaml
  - ingress-atlantis.yaml
  # - ingress-kiali.yaml
  - ingress-kubecost.yaml
  - ingress-linkerd.yaml
  - ingress-longhorn.yaml
  - ingress-motioneye.yaml
  - ingress-n8n.yaml
  - ingress-rancher.yaml
  - ingress-scope.yaml
  # - ingress-skydive.yaml
  - ingress.yaml
  - service.yaml