apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-db
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/approvals: "1"
    keel.sh/pollSchedule: "@every 1m"
  labels:
    app: nextcloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  serviceName: nextcloud-db
  template:
    metadata:
      annotations:
        # linkerd.io/inject: enabled
      labels:
        app: nextcloud-db
    spec:
      containers:
        - name: nextcloud-db
          image: mariadb:10.5
          imagePullPolicy: Always
          envFrom:
          - secretRef:
              name: nextcloud-db
          ports:
            - containerPort: 3306
              name: sql
              protocol: TCP
          volumeMounts:
            - name: nextcloud-db
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 750m
              memory: 768Mi
            requests:
              cpu: 750m
              memory: 768Mi
      nodeSelector:
        longhorn: primary-pool
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nextcloud-db
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-cache
  annotations:
    keel.sh/policy: all
    keel.sh/trigger: poll
    keel.sh/approvals: "1"
    keel.sh/pollSchedule: "@every 1m"
    # fluxcd.io/ignore: "true"
  labels:
    app: nextcloud-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-cache
  serviceName: nextcloud-cache
  template:
    metadata:
      annotations:
        # linkerd.io/inject: enabled
      labels:
        app: nextcloud-cache
    spec:
      containers:
        - name: nextcloud-cache
          image: redis:6.2
          imagePullPolicy: Always
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: nextcloud-cache
              mountPath: /data
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
      nodeSelector:
        longhorn: primary-pool
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nextcloud-cache
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
