apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-db
  labels:
    app: nextcloud-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-db
  serviceName: nextcloud-db
  template:
    metadata:
      labels:
        app: nextcloud-db
    spec:
      containers:
        - name: nextcloud-db
          image: mariadb:10.5
          envFrom:
          - secretRef:
              name: nextcloud-db
          ports:
            - containerPort: 3306
              name: sql
              protocol: TCP
          volumeMounts:
            - name: nextcloud-db
              mountPath: /var/lib/mysql
          resources:
            limits:
              cpu: 250m
              memory: 768Mi
            requests:
              cpu: 250m
              memory: 768Mi
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nextcloud-db
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 5Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud-cache
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: nextcloud-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud-cache
  serviceName: nextcloud-cache
  template:
    metadata:
      labels:
        app: nextcloud-cache
    spec:
      containers:
        - name: nextcloud-cache
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: nextcloud-cache
              mountPath: /data
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nextcloud-cache
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nextcloud
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: nextcloud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - nextcloud-cache
      #       topologyKey: kubernetes.io/hostname
      containers:
      - name: nextcloud
        image: nextcloud:20.0.7
        imagePullPolicy: IfNotPresent
        # command: ["tail","-f","/dev/null"]
        envFrom:
          - secretRef:
              name: nextcloud-config
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
          - mountPath: "/var/www/html"
            name: nextcloud-data
        resources:
          requests:
            #cpu: 1000m
            memory: 1Gi
          limits:
            #cpu: 1000m
            memory: 1Gi
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: nextcloud-data
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 240Gi