apiVersion: v1
kind: Service
metadata:
  name: electrumx
spec:
  type: LoadBalancer
  selector:
    app: electrumx
  ports:
    - name: electrumx
      protocol: TCP
      port: 50002
      targetPort: 50002
