# pulled from https://github.com/richstokes/k8s-fah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-server
  annotations:
    install.operator.istio.io/version: 1
  labels:
    app: iperf3-server
spec:
  selector:
    matchLabels:
      app: iperf3-server
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: iperf3-server
    spec:
      containers:
        - name: iperf3
          image: networkstatic/iperf3:latest
          args: ["-s"]
---
# pulled from https://github.com/richstokes/k8s-fah
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf3-client
  labels:
    app: iperf3-client
spec:
  selector:
    matchLabels:
      app: iperf3-client
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
      maxSurge: 100%
  template:
    metadata:
      labels:
        app: iperf3-client
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - iperf3-server
            topologyKey: "kubernetes.io/hostname"

      containers:
        - name: iperf3-client
          image: networkstatic/iperf3:latest
          args: ["-c","iperf3-server","-t","0"]
