apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shared-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: btc-rpc-explorer.jura
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: btc-rpc-explorer
            port:
              number: 80