apiVersion: apps/v1
kind: Deployment
metadata:
  name: btc-rpc-explorer
  labels:
    app: btc-rpc-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-rpc-explorer
  template:
    metadata:
      labels:
        app: btc-rpc-explorer
    spec:
      containers:
        - name: btc-rpc-explorer
          image: tyzbit/btc-rpc-explorer
          imagePullPolicy: Always
          env:
            - name: BTCEXP_HOST
              value: "0.0.0.0"
            - name: BTCEXP_ADDRESS_API
              value: electrumx
            - name: BTCEXP_REDIS_URL
              value: redis://127.0.0.1:6379
            - name: BTCEXP_NO_RATES
              value: "false"
            - name: BTCEXP_SLOW_DEVICE_MODE
              value: "false"
          envFrom:
            - secretRef:
                name: btc-rpc-explorer
          ports:
            - containerPort: 3002
              name: http
              protocol: TCP
          resources:
            limits:
              memory: 256M
            requests:
              memory: 256M
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          resources:
            limits:
              cpu: 100m
              memory: 128M
            requests:
              cpu: 100m
              memory: 128M
