apiVersion: apps/v1
kind: Deployment
metadata:
  name: bitcoin-rpc-explorer
  labels:
    app: bitcoin-rpc-explorer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bitcoin-rpc-explorer
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: bitcoin-rpc-explorer
    spec:
      containers:
      - name: bitcoin-rpc-explorer
        image: tyzbit/bitcoin-rpc-explorer
        imagePullPolicy: Always
        env:
          - name: BTCEXP_HOST
            value: "0.0.0.0"
          - name: BTCEXP_BITCOIN_URI
            valueFrom:
              secretKeyRef:
                - name: bitcoin-rpc-explorer
                  key: BTCEXP_BITCOIN_URI
        ports:
        - containerPort: 3002
          name: http
          protocol: TCP
        resources:
          limits:
            memory: 2G
