apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc-rpc-explorer-cache
  labels:
    app: btc-rpc-explorer-cache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: btc-rpc-explorer-cache
  serviceName: btc-rpc-explorer-cache
  template:
    metadata:
      labels:
        app: btc-rpc-explorer-cache
    spec:
      containers:
        - name: redis
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: btc-rpc-explorer-cache
              mountPath: /data
          resources:
            limits:
              cpu: 100m
              memory: 128M
            requests:
              cpu: 100m
              memory: 128M
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: btc-rpc-explorer-cache
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
