apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: btc-rpc-explorer-cache
  labels:
    app: btc-rpc-explorer-cache
spec:
  replicas: 0
  selector:
    matchLabels:
      app: btc-rpc-explorer-cache
  serviceName: btc-rpc-explorer-cache
  template:
    metadata:
      labels:
        app: btc-rpc-explorer-cache
    spec:
      # affinity:
      #   podAffinity:
      #     requiredDuringSchedulingIgnoredDuringExecution:
      #     - labelSelector:
      #         matchExpressions:
      #         - key: app
      #           operator: In
      #           values:
      #           - bitcoin
      #           - btc-rpc-explorer
      #           - electrumx
      #       topologyKey: kubernetes.io/hostname
      containers:
        - name: btc-rpc-explorer-cache
          image: redis
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            - name: btc-rpc-explorer-cache
              mountPath: /data
          resources:
            limits:
              cpu: 50m
              memory: 128Mi
            requests:
              cpu: 50m
              memory: 128Mi
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: btc-rpc-explorer-cache
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 2Gi
