apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-dl
  template:
    metadata:
      labels:
        app: youtube-dl
    spec:
      containers:
      - name: youtube-dl
        image: tzahi12345/youtubedl-material:latest
        # command: ["tail","-f","/dev/null"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8998
          name: youtube-dl
          protocol: TCP
        volumeMounts:
          - mountPath: /app/audio
            name: youtube-dl-audio
          - mountPath: /app/video
            name: youtube-dl-video
          - mountPath: /app/appdata
            name: youtube-dl-appdata
          - mountPath: /app/users
            name: youtube-dl-users
          - mountPath: /app/subscriptions
            name: youtube-dl-subscriptions
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M
      volumes:
        - name: youtube-dl-audio
          persistentVolumeClaim:
            claimName: youtube-dl-audio
        - name: youtube-dl-video
          persistentVolumeClaim:
            claimName: youtube-dl-video
        - name: youtube-dl-appdata
          persistentVolumeClaim:
            claimName: youtube-dl-appdata
        - name: youtube-dl-users
          persistentVolumeClaim:
            claimName: youtube-dl-users
        - name: youtube-dl-subscriptions
          persistentVolumeClaim:
            claimName: youtube-dl-subscriptions
