apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-audio
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 40Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-video
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-appdata
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-subscriptions
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: youtube-dl-users
spec:
  accessModes: 
    - ReadWriteMany
  volumeMode: Filesystem
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi