apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: youtube-dl
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-dl
  serviceName: youtube-dl
  template:
    metadata:
      annotations:
        # linkerd.io/inject: enabled
      labels:
        app: youtube-dl
    spec:
      containers:
      - name: youtube-dl
        image: tzahi12345/youtubedl-material:nightly
        # command: ["tail","-f","/dev/null"]
        command: ["sh","-c","npm i nodemon -g && /app/entrypoint.sh nodemon app.js"]
        imagePullPolicy: Always
        env: 
        - name: ALLOW_CONFIG_MUTATIONS
          value: "true"
        ports:
        - containerPort: 17442
          name: http-youtube-dl
          protocol: TCP
        volumeMounts:
          - mountPath: /app/audio
            name: youtube-dl-audio
          - mountPath: /app/video
            name: youtube-dl-video
          - mountPath: /app/appdata
            name: youtube-dl-appdata
          - mountPath: /app/users
            name: youtube-dl-users
          - mountPath: /app/subscriptions
            name: youtube-dl-subscriptions
        resources:
          requests:
            cpu: 500m
            memory: 2048Mi
          limits:
            cpu: 500m
            memory: 2048Mi
        livenessProbe:
          initialDelaySeconds: 60
          httpGet:
            port: http-youtube-dl
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-audio
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-video
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-appdata
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-subscriptions
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-users
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 10Gi