apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: youtube-dl
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-dl
  serviceName: youtube-dl
  template:
    metadata:
      annotations:
      # linkerd.io/inject: enabled
      labels:
        app: youtube-dl
    spec:
      # this is really only needed the very first time this deployment is executed
      initContainers:
        - name: youtube-dl-createdirs
          image: busybox
          command:
            - sh
            - -c
            - for d in appdata audio subscriptions users video; do mkdir /app/$d; done
          volumeMounts:
            - mountPath: /app
              name: youtube-dl-data
      containers:
        - name: youtube-dl
          image: tzahi12345/youtubedl-material:nightly
          # command: ["tail","-f","/dev/null"]
          # command: ["sh","-c","npm i nodemon -g && /app/entrypoint.sh nodemon app.js"]
          imagePullPolicy: Always
          env:
            - name: ALLOW_CONFIG_MUTATIONS
              value: "true"
          ports:
            - containerPort: 17442
              name: http-youtube-dl
              protocol: TCP
          volumeMounts:
          # mount specific subdirectories so as not to clobber the files in /app
            - mountPath: /app/appdata
              subpath: appdata
              name: youtube-dl-data
            - mountPath: /app/audio
              subpath: audio
              name: youtube-dl-data
            - mountPath: /app/subscriptions
              subpath: subscriptions
              name: youtube-dl-data
            - mountPath: /app/users
              subpath: users
              name: youtube-dl-data
            - mountPath: /app/video
              subpath: video
              name: youtube-dl-data
          resources:
            requests:
              cpu: 500m
              memory: 2048Mi
            limits:
              cpu: 500m
              memory: 2048Mi
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              port: http-youtube-dl
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: youtube-dl-data
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        storageClassName: longhorn
        resources:
          requests:
            storage: 20Gi
