apiVersion: apps/v1
kind: Deployment
metadata:
  name: youtube-dl
  annotations:
    # fluxcd.io/ignore: "true"
  labels:
    app: youtube-dl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youtube-dl
  template:
    metadata:
      labels:
        app: youtube-dl
    spec:
      containers:
      - name: youtube-dl
        image: tzahi12345/youtubedl-material:latest
        # command: ["tail","-f","/dev/null"]
        imagePullPolicy: Always
        ports:
        - containerPort: 8998
          name: youtube-dl
          protocol: TCP
        volumeMounts:
          - mountPath: /app/appdata
            name: youtube-dl-appdata
          - mountPath: /app/audio
            name: youtube-dl-audio
          - mountPath: /app/video
            name: youtube-dl-video
          - mountPath: /app/subscriptions
            name: youtube-dl-subscriptions
          - mountPath: /app/users
            name: youtube-dl-users
        resources:
          requests:
            memory: 512M
          limits:
            memory: 512M
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-audio
    spec:
      accessModes: 
        - ReadWriteMany
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 40Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-video
    spec:
      accessModes: 
        - ReadWriteMany
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 100Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-appdata
    spec:
      accessModes: 
        - ReadWriteMany
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-subscriptions
    spec:
      accessModes: 
        - ReadWriteMany
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: youtube-dl-users
    spec:
      accessModes: 
        - ReadWriteMany
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi