apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: huginn
  labels:
    app: huginn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: huginn
  serviceName: huginn
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: huginn
    spec:
      containers:
        - name: huginn
          image: huginn/huginn:latest
          #command: ["tail","-f","/dev/null"]
          envFrom:
          - secretRef:
              name: huginn-config
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
          volumeMounts:
            - name: huginn-db-data
              mountPath: /var/lib/mysql
          resources:
            limits:
              #cpu: 500m
              memory: 512Mi
            requests:
              #cpu: 500m
              memory: 512Mi
      imagePullSecrets:
        - name: docker-hub
  volumeClaimTemplates:
  - apiVersion: v1
    kind: PersistentVolume
    metadata:
      name: huginn-db-data
    spec:
      accessModes: 
        - ReadWriteOnce
      volumeMode: Filesystem
      storageClassName: longhorn
      resources:
        requests:
          storage: 1Gi
