apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inspector-configs
  namespace: {{ .Values.namespace }}
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: nfs-client
  accessModes: 
    - ReadWriteMany
