apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inspector-configs
spec:
  accessModes: 
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi