apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoin-blockchain
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 750Gi
