apiVersion: v1
kind: Service
metadata:
  name: bitcoin
spec:
  type: LoadBalancer
  selector:
    app: bitcoin
  ports:
    - name: bitcoin
      protocol: TCP
      port: 8333
      targetPort: 8333
    - name: bitcoin-rpc
      protocol: TCP
      port: 8332
      targetPort: 8332
    - name: bitcoin-mq
      protocol: TCP
      port: 28332
      targetPort: 28332
    - name: bitcoin-mq2
      protocol: TCP
      port: 28333
      targetPort: 28333
